"""drop_assistant_and_course_assistant_tables

Revision ID: 00fa352db6f0
Revises: 
Create Date: 2026-02-25 13:13:29.051785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fa352db6f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use IF EXISTS to safely skip drops on a fresh database
    # where these tables were never created.
    op.execute('DROP TABLE IF EXISTS course_assistants')
    op.execute('DROP TABLE IF EXISTS assistants')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistants',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('assistants_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assistants_pkey'))
    )
    op.create_table('course_assistants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assistant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('section_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], name=op.f('course_assistants_assistant_id_fkey')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('course_assistants_course_id_fkey')),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('course_assistants_section_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_assistants_pkey'))
    )
    # ### end Alembic commands ###
