"""add_course_professors_table

Revision ID: d95312977e64
Revises: 256567706b8a
Create Date: 2026-02-25 13:59:14.993156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95312977e64'
down_revision: Union[str, Sequence[str], None] = '256567706b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use IF EXISTS to safely skip on fresh databases where professor_id
    # column on courses was never added (it was a pre-migration schema state).
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name='courses' AND column_name='professor_id'
            ) THEN
                ALTER TABLE courses DROP CONSTRAINT IF EXISTS courses_professor_id_fkey;
                ALTER TABLE courses DROP COLUMN IF EXISTS professor_id;
            END IF;
        END$$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('professor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('courses_professor_id_fkey'), 'courses', 'professors', ['professor_id'], ['id'])
    # ### end Alembic commands ###
